### ISSUE TITLE
Possible correction of Auxiliary Ravno in final place in typesetting sequences

### ISSUE THREAD

**Issue by starover77** [slavonic/fonts-znam#10]
It would be a great idea to resolve the current necessity of typesetting an auxiliary Ravno as the final neume in a sequence, which is illogical musically, but necessary for display. As we had discussed, this may not ever be possible.

**Comment by typiconman** [comment]
Are there any instances where the ravno exists together with pitch marks where it should not be an auxiliiary ravno?

Are there any instances where two or more ravno marks are placed along one neume?

**Comment by starover77** [comment]
For the first question, I don't think so. By adding a Ravno after a pitch mark, it contextually becomes an auxiliary pitch mark, and I don't think there can be an exception.

Regarding two or more Ravno marks: You can have two Ravno marks where the first one is a full Ravno and the second one is an auxiliary mark. See Kalashnikov 310-316. More than 2 is something I've never encountered.

I will compile a list of all the usages of the auxiliary Ravno and test them to see what is working and what is not. But essentially my point is that the way we have to trick the auxiliary ravno to display correctly is to defer its placement to the last character of a sequence, which separates it from the logical order of where its function is being applied. Using this method of character entry, we could not write an algorithm to convert the neumatic notation to modern musical notation because the code could not interpret where the aux. Ravno takes affect in the sequence. It is my hope that we can find a logical solution to fix this, but I am also aware that a viable solution may not be possible.

**Comment by starover77** [comment]
Here is the list of usages of the Auxiliary Ravno in Demestvenny notation. (The usages in Znamenny notation seem to check out OK.)

K=Kalashnikov's Azbuka, P=Pozhidaeva's catalog

Sequences which work correctly and in correct (logical) order:
K. 4, 14, 34, 149, 253, 254, 255.
P. 70 (although this one is dubious).

Sequences which don't work, even when switching the auxiliary ravno to the final position:
K. 31, 129, 131, 135, 147, 150.
P. 74, 81, 200.

I copied all these into a document to work with as this project goes forward, and I will send it to you separately by email.

**Comment by starover77** [comment]
I sent you a document for testing all these.

**Comment by typiconman** [comment]
@starover77 I think this is resolved, yes?

**Comment by starover77** [comment]
This has been resolved. I will close the issue.
