### ISSUE TITLE
Solutions needed for the alternate placement of pitch marks

### ISSUE THREAD

**Issue by starover77** [slavonic/fonts-znam#11]
We need to find solutions for the alternate placement of pitch marks. While the pitch mark placements are now fully resolved for Znamenny notation, there remain several complex placement issues for Kalashnikov's version of Demestvenny notation. One solution we had discussed was to use the Combining Grapheme Joiner to disrupt the sequence of pitch stacking. I am compiling a list of these problematic neumes and providing images of them to guide us in this work.

**Comment by starover77** [comment]
Probably the most urgent need is for the addition of a method of displaying a pitch at the end of a neume, on the lower right side instead of the default upper left side. This informs the singer of the final pitch in a complex sequence.

**Comment by typiconman** [comment]
@starover77 We've taken care of this, yes?

**Comment by starover77** [comment]
This has been resolved. I will close the issue.
