### ISSUE TITLE
New GSUB needs to be added

### ISSUE THREAD

**Issue by starover77** [slavonic/fonts-znam#13]
For Demestvenny notation, the seldom-used sequence of Skameitsa klyuchevaya (U+1CF75) plus Slozhitie (U+1CF7D) forms a ligature that cannot be conveniently produced by kerning, as the amount of kerning would be excessive and the anchor points would be problematic. I propose that we add a lookup to point to a newly-added composite (or contracted) character at U+EC11.

**Comment by typiconman** [comment]
@starover77 I believe this is now done. Please check.

**Comment by starover77** [comment]
This has been resolved. I will close the issue.
