### ISSUE TITLE
Support OpenType-SVG

### ISSUE THREAD

**Issue by typiconman** [slavonic/fonts-znam#18]
Right now color is handled via COLR/CPAL. We should also support the new OpenType-SVG standard:
See [here](https://github.com/adobe-type-tools/opentype-svg); support is described [here](https://helpx.adobe.com/fonts/using/ot-svg-color-fonts.html)

**Comment by typiconman** [comment]
I added support for OpenType-SVG. However, I have no way of testing it, since I don't own Adobe products. 
@starover77 Can you test the attached font file in Illustrator, Photoshop or InDesign to see if the cinnabar marks are colored automatically?
[MezenetsUnicode.zip](https://github.com/slavonic/fonts-znam/files/3884024/MezenetsUnicode.zip)

**Comment by starover77** [comment]
I'm sorry, but I only have Photoshop and it's on my Mac. The version I have installed is at least 10 years old.

**Comment by typiconman** [comment]
Too bad. Then I guess will have to say that we have OpenType-SVG support, but no way of testing it.
@named-entity Perhaps you can test it on an Adobe product?

**Comment by typiconman** [comment]
Closing the issue. I consider this fixed until and unless someone comments that it doesn't work as expected. OpenType-SVG support added, but not tested.
