### ISSUE TITLE
Fix position of Sorochya Nozhka

### ISSUE THREAD

**Issue by typiconman** [slavonic/fonts-znam#3]
Sorochya Nozkha U+1CF3A is not being positioned correctly on the Stopitsa s Ochkom U+1CF57, Perevodka U+1CF58, etc.

**Comment by starover77** [comment]
I have fixed all of these, including the base neumes and their corresponding variants in the PUA. Please test one more time before closing this issue.

BTW: When I was working on this issue, I fixed a few other inconsistencies in the positioning of the anchor points for a few other neumes, in an attempt to ensure that the PUA variants have identical behaviors with their base neumes.

**Comment by typiconman** [comment]
Fixed by d5944cf8346626ab079c949b628f8923808658d4.
