### ISSUE TITLE
Adding stylistic set for Kalashnikov mechiki

### ISSUE THREAD

**Issue by typiconman** [slavonic/fonts-znam#4]
There should be a stylistic set ss02 that allows the Kalashnikov-style mechiki to be selected. E.g. U+1CFAA should map to U+EFE6, etc.

**Comment by typiconman** [comment]
We also need to implement lookups for the priznakified Kalashnikov mechiki. I may need some guidance on this one.

**Comment by starover77** [comment]
Have we resolved this now?

**Comment by typiconman** [comment]
Can you come up with a document to test that this works correctly?

**Comment by starover77** [comment]
I'm not sure that we can test these until the new system of priznaki triggers are added (P2, P3, P4, P5). Let me know how I should proceed here. Thanks.

**Comment by typiconman** [comment]
That's  a good point. I haven't made up my mind yet about the priznaki controls. Let's focus on the anchor point stuff first.

**Comment by typiconman** [comment]
@starover77 This works correctly, yes?

**Comment by starover77** [comment]
This has been resolved. I will close the issue.
