### ISSUE TITLE
Changes to PUA - blue subzone

### ISSUE THREAD

**Issue by starover77** [slavonic/fonts-znam#7]
Here is a TODO for changes to the PUA (blue subzone), best done in this order:

1) Move the following four characters into the PUA (by swapping them out and then deleting the unneeded ones):
U+1CF70 to U+EAC5 (chaska polnaya)
U+1CF87 to U+EAFA (zmeitsa)
U+1CFC3 to U+EB5E (truba)
U+1CFC6 to U+EB5F (pauk velikii)

2) Delete U+EB20 and U+EB22.

3) Move U+EB5B and U+EB5C into the two slots that were just vacated in #2 above.

4) Move U+EB58 and U+EB59 into the two empty slots at U+EADA and U+EADB.

5) Move U+EB35 to U+EB32.

6) Move U+EB52 to the slot that was just vacated at U+EB35.

7) Move U+EB51 to U+EAC8.

8) Add lookups to the following new characters:
U+EA9E
U+EABC
U+EABD
U+EB37

**Comment by typiconman** [comment]
A question regarding U+EA9E -- what is the lookup for this? How will this glyph be accessed?

Also, what to do with U+EB5B and U+EB5C -- are these stylistic variants?

What is the lookup for U+EB37? How is this glyph accessed?

**Comment by starover77** [comment]
U+EA9E is an oddball neume that appears in at least one manuscript, and I thought it would be good to include this "just in case", but I am not sure what is the best methodology here. It is called "Palka tresvetlaya", but this is nonsensical to us. We could perhaps enter it as a Palka + tochka + dvoetochie, or Palka + tresvetlo mark. If no logical method is available, I am content to just let it hang out without any method of typesetting it, except to access it directly in the PUA.

U+EB5B and U+EB5C are stylistic variants, seen (I believe) in the neume tables in "Kliuch znamennoi" (iKhristofor, 1604).

U+EB37 (and U+EB36) seem like they should be base neumes, but they are only included in a couple azbuki that were collected by Shindin, and neither of them seem to show up in actual musical settings that I've seen. Both U+EB36 and EB37 seem to be theoretical constructs. How is EB36 entered? Perhaps EB37 could be entered in a similar manner. If no logical method is available, I am content to just let both of them hang out without any method of typesetting them, except to access them directly in the PUA.

**Comment by typiconman** [comment]
Right now U+EB36 and U+EB37 are accessible only directly from the PUA.

Shindin or Shabalin?

**Comment by starover77** [comment]
Sorry. That was Shabalin. Just waking up on this side of the planet.

**Comment by typiconman** [comment]
Does he provide a source for these neumes? If they do actually exist, we could encode them, rather than putting them in the PUA.

**Comment by starover77** [comment]
Regarding U+EB36 and U+EB37.... I don't think we have a choice but to leave them as they are, with no direct access. These are not constructed in a manner that they can be composed.

**Comment by starover77** [comment]
Well, everything in the tables of azbuki came from a source, as his book reproduces a very large number of musical manuscripts. Let me see if I can dig up sources, and I will get back to you shortly.

**Comment by starover77** [comment]
For U+EB37, I have located it in Shabalin, volume 1, page 274 (ПГБ, ф/ 379, сер. 90-х гг. XVII в., л. 62-64). Oddly, it is called "Непостоянной мечик" in the original source, but I don't agree with that name.

Regarding U+EB36, it seems that Murphy's Law is in effect today, as I can't find where I originally saw it. I have been extremely cautious to only include items in the PUA that I have been able to genuinely find, so I have no doubt of its authenticity *somethere*, but I can't locate it an any of the expected manuscripts right now.

In both cases, I am sceptical of their authenticity as base neumes, and I tend to think that they are scribal errors (especially in the case of EB37, which is likely to be an error for U+1CFAE (or what was in that place up to this point in time). I am in favor of letting them remain in the PUA, although if you want to include EB37, we do have a documentable case here, and it could make a bit of sense as a musical symbol. -- However, any case for EB36 is weak, as it doesn't make any sense as a musical construct. With the exception of the Simple Arrow, none of the other arrows have an analogous construct.

**Comment by typiconman** [comment]
Here is the manuscript in question:
http://old.stsl.ru/manuscripts/f-379/19?fnum=70

And here is zoom up of the character in question (EB37):
![379-019-0070](https://user-images.githubusercontent.com/5428695/51231142-808a6e00-1973-11e9-8406-dd6486e86389.jpg)

I'm inclined to encode this in Unicode as an analog to U+1CFAB, unless you think it's nonce.
The others I'm inclined to leave in the PUA. We seem to have no logical way of accessing U+EA9E.

**Comment by starover77** [comment]
I am quite familiar with this manuscript, although I had long ago discounted it as a trustworthy source, as it is abundantly obvious that the scribe or copyist had no idea what he was doing and was not at all familiar with Put notation. The quantity and quality of mistakes in nomenclature alone is the biggest clue, as is the lack of connection between many of the names and neumes.

What is interesting here is that this manuscript likewise provides us with another example of the nonce Palka tresvetlaya at U+EA9E. I am content to let it remain in the PUA without composition or keyboard access.

As for the character in question (EB37), I am still not convinced of its validity, but I am willing to consider it as valid, since its construction has some logic which makes some level of sense, and we have some manuscript evidence (at least 2 sources) which claim it to be a "thing". We just might end up encountering it in some manuscripts and find that we need it after all.

BTW: If you do end up adding this "Mechik povodnyi" to the proposal, would it be possible to move the Mechik with Cross (was at EB52) into the spot being vacated (EB37), instead of where I asked earlier? That would be the best place for it, as it would preserve proper character ordering.

**Comment by typiconman** [comment]
I think I've taken care of this issue. @starover77 please review and close.
